### ISSUE TITLE
Regarding pi-GAN results

### ISSUE THREAD

**Issue by HexagonPrime** [apple/ml-gsn#2]
Hello,

Congrats for producing such amazing work! Can't wait for the code release(if there will be one).
I have a small question regarding pi-GAN results...Did you implement your own version? It seems the available non-official implementations are not completely correct(https://github.com/lucidrains/pi-GAN-pytorch/issues/4).

Best regards.

**Comment by mbautistamartin** [comment]
Hi there! Thanks for your kind words! We have just released an official implementation of GSN with corresponding training data and pre-trained models. Although it's not included with this release we implemented our own version of pi-gan and spend a substantial amount of time using it.
