### ISSUE TITLE
Release the training data for Replica dataset?

### ISSUE THREAD

**Issue by MultiPath** [apple/ml-gsn#3]
Hi, thank you for the very nice work!
I am wondering how do you generate the training data on Replica dataset.

Based on your paper, you mentioned: "To generate data for the VizDoom and Replica experiments we render 100 sequences of 100 steps each, where an interactive agent explores a scene collecting RGB and depth observations as well as camera poses"

How can we reproduce this? Will you plan to release the dataset first?
Thank you very much!

**Comment by mbautistamartin** [comment]
Hi there! Thanks for your interest in our repo, we have just released an official implementation with corresponding training data and pre-trained models.

**Comment by MultiPath** [comment]
Thanks!
